INITIAL_VERSION = "1.0.1"

UPLOAD_PYPI = "1.0.2"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

WORK_ON_WINDOWS = "1.2.0"

NEW_VERSION_NAME = "1.2.1"

INTERESTING_PATH_SHOWN = "1.2.2"

INTERESTING_PATH_SHOWN = "1.2.2"

VERSION = INTERESTING_PATH_SHOWN
