INITIAL_VERSION = "1.0.1"

UPLOAD_PYPI = "1.0.2"


UPLOAD_PYPI = "1.0.3"

UPLOAD_PYPI = "1.0.4"

ADD_DOCUMENTATION_IN_BUILD = "1.0.5"

ADD_DOCUMENTATION_IN_BUILD = "1.0.5"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

ADD_DOCUMENTATION_IN_BUILD = "1.1.0"

VERSION = ADD_DOCUMENTATION_IN_BUILD
